version: '3'
services:
  bootstrap:
    image: calee0219/docker-geth-cluster
    container_name: bootstrap
    entrypoint: /usr/bin/geth
    command: "--networkid 110010 --nodekeyhex 091bd6067cb4612df85d9c1ff85cc47f259ced4d4cd99816b14f35650f59c322 --rpc --rpcaddr 0.0.0.0"
    expose:
      - "30303"
      - "8545"
    networks:
      privnet:
        ipv4_address: 10.5.0.100

  eth:
    image: calee0219/docker-geth-cluster
    links:
      - bootstrap
    entrypoint: /usr/bin/geth
    command: "--networkid 110010 --bootnodes enode://288b97262895b1c7ec61cf314c2e2004407d0a5dc77566877aad1f2a36659c8b698f4b56fd06c4a0c0bf007b4cfb3e7122d907da3b005fa90e724441902eb19e@10.5.0.100:30303 --rpc --rpcaddr 0.0.0.0"
    expose:
      - "30303"
      - "8545"
    networks:
      - privnet

  miner:
    image: calee0219/docker-geth-cluster
    links:
      - bootstrap
    command: bash -c "geth --password <(echo -n 110010) account new && geth --networkid 110010 --bootnodes enode://288b97262895b1c7ec61cf314c2e2004407d0a5dc77566877aad1f2a36659c8b698f4b56fd06c4a0c0bf007b4cfb3e7122d907da3b005fa90e724441902eb19e@10.5.0.100:30303 --rpc --rpcaddr 0.0.0.0 --mine"
    expose:
      - "30303"
      - "8545"
    networks:
      - privnet

networks:
  privnet:
    driver: bridge
    ipam:
      config:
        - subnet: 10.5.0.0/24